import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { 
  PieChart, Pie, Cell, BarChart, Bar, XAxis, Tooltip, ResponsiveContainer, Legend
} from 'recharts';
import { motion } from 'framer-motion';
import { 
  TrendingUp, CheckCircle, Brain, RefreshCw
} from 'lucide-react';
import type { FinancialResult } from '../utils/finance';

const COLORS = ['#10b981', '#ef4444', '#f59e0b', '#6366f1'];

import { AIChatBox } from '../components/AIChatBox';

export const Dashboard = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [result, setResult] = useState<FinancialResult | null>(null);
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (location.state?.result) {
      // Simulate AI processing time
      setTimeout(() => {
        setResult(location.state.result);
        setData(location.state.data);
        setLoading(false);
      }, 2000);
    } else {
      navigate('/');
    }
  }, [location, navigate]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-4">
        <div className="w-16 h-16 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin"></div>
        <p className="text-lg font-medium text-gray-600 dark:text-gray-300 animate-pulse">
          AI is analyzing your financial health...
        </p>
      </div>
    );
  }

  if (!result) return null;

  const scoreColor = result.score >= 80 ? 'text-emerald-500' : result.score >= 50 ? 'text-yellow-500' : 'text-red-500';
  const riskColor = result.riskLevel === 'Excellent' ? 'bg-emerald-100 text-emerald-800' : result.riskLevel === 'Moderate' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800';

  const pieData = [
    { name: 'Savings', value: Math.max(0, result.savingsRatio) },
    { name: 'Expenses', value: result.expenseRatio },
    { name: 'Debt', value: result.debtRatio },
  ];

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Financial Health Report</h1>
          <p className="text-gray-500 dark:text-gray-400">Generated by AI Advisor • {new Date().toLocaleDateString()}</p>
        </div>
        <span className={`px-4 py-2 rounded-full font-bold text-sm uppercase tracking-wide ${riskColor}`}>
          {result.riskLevel} Risk
        </span>
      </div>

      {/* Main Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Score Card */}
        <div className="md:col-span-1 bg-white dark:bg-slate-800 rounded-2xl shadow-sm p-6 flex flex-col items-center justify-center relative overflow-hidden border border-gray-100 dark:border-slate-700 min-h-[300px]">
          <div className="absolute inset-0 bg-gradient-to-br from-indigo-50/50 to-transparent pointer-events-none dark:from-indigo-900/10" />
          <h3 className="text-gray-500 font-medium mb-4 z-10">Overall Score</h3>
          <div className="relative w-48 h-48 flex items-center justify-center">
             <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={[{ value: result.score }, { value: 100 - result.score }]}
                    innerRadius={70}
                    outerRadius={90}
                    startAngle={90}
                    endAngle={-270}
                    dataKey="value"
                    stroke="none"
                  >
                    <Cell fill={result.score >= 80 ? '#10b981' : result.score >= 50 ? '#f59e0b' : '#ef4444'} />
                    <Cell fill="#e2e8f0" />
                  </Pie>
                </PieChart>
             </ResponsiveContainer>
             <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className={`text-5xl font-bold ${scoreColor}`}>{result.score}</span>
                <span className="text-sm text-gray-400">/100</span>
             </div>
          </div>
        </div>

        {/* Breakdown Charts */}
        <div className="md:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-6">
           {/* Income vs Expense */}
           <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm p-6 border border-gray-100 dark:border-slate-700">
             <h3 className="text-gray-500 font-medium mb-4">Cash Flow</h3>
             <div className="h-48 w-full">
               <ResponsiveContainer width="100%" height="100%">
                 <BarChart data={[
                   { name: 'In', amount: result.incomeTotal },
                   { name: 'Out', amount: result.totalExpenses },
                 ]} barSize={40}>
                   <XAxis dataKey="name" axisLine={false} tickLine={false} />
                   <Tooltip 
                     formatter={(value: any) => `₹${Number(value).toLocaleString('en-IN')}`}
                     cursor={{ fill: 'transparent' }} 
                     contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} 
                   />
                   <Bar dataKey="amount" radius={[4, 4, 0, 0]}>
                     {
                       [0, 1].map((_, index) => (
                         <Cell key={`cell-${index}`} fill={index === 0 ? '#4f46e5' : '#ef4444'} />
                       ))
                     }
                   </Bar>
                 </BarChart>
               </ResponsiveContainer>
             </div>
           </div>

           {/* Financial Distribution Pie */}
           <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm p-6 border border-gray-100 dark:border-slate-700">
             <h3 className="text-gray-500 font-medium mb-4">Financial Ratios</h3>
             <div className="h-48 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={pieData}
                      innerRadius={40}
                      outerRadius={60}
                      paddingAngle={5}
                      dataKey="value"
                    >
                      {pieData.map((_, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip contentStyle={{ borderRadius: '8px', border: 'none' }} itemStyle={{ color: '#333' }} />
                    <Legend verticalAlign="bottom" height={36}/>
                  </PieChart>
                </ResponsiveContainer>
             </div>
           </div>
        </div>
      </div>

      {/* AI Suggestions */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-gradient-to-br from-indigo-600 to-violet-700 rounded-2xl p-6 text-white shadow-lg"
        >
          <div className="flex items-center space-x-3 mb-6">
            <div className="p-2 bg-white/20 rounded-lg backdrop-blur-sm">
              <Brain className="w-6 h-6 text-white" />
            </div>
            <h3 className="text-xl font-bold">AI Recommendations</h3>
          </div>
          <div className="space-y-4">
            {result.suggestions.map((suggestion, index) => (
              <div key={index} className="flex items-start space-x-3 bg-white/10 rounded-xl p-4 backdrop-blur-sm border border-white/10">
                <CheckCircle className="w-5 h-5 text-emerald-300 mt-0.5 shrink-0" />
                <p className="text-sm md:text-base text-indigo-50 font-medium leading-relaxed">
                  {suggestion}
                </p>
              </div>
            ))}
            {result.suggestions.length === 0 && (
               <div className="flex items-start space-x-3 bg-white/10 rounded-xl p-4 backdrop-blur-sm">
                <CheckCircle className="w-5 h-5 text-emerald-300" />
                <p className="text-indigo-50">Great job! Your financial health looks solid. Keep monitoring your expenses.</p>
              </div>
            )}
          </div>
        </motion.div>

        {/* Roadmap */}
        <motion.div 
           initial={{ opacity: 0, x: 20 }}
           animate={{ opacity: 1, x: 0 }}
           transition={{ delay: 0.4 }}
           className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-slate-700"
        >
           <div className="flex items-center space-x-3 mb-6">
            <div className="p-2 bg-emerald-100 dark:bg-emerald-900/30 rounded-lg">
              <TrendingUp className="w-6 h-6 text-emerald-600 dark:text-emerald-400" />
            </div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white">6-Month Roadmap</h3>
          </div>
          
          <div className="relative pl-8 border-l-2 border-indigo-100 dark:border-slate-700 space-y-8">
            {result.roadmap.map((step, index) => (
              <div key={index} className="relative">
                <span className="absolute -left-[39px] top-1 h-5 w-5 rounded-full border-4 border-white dark:border-slate-800 bg-indigo-600 ring-4 ring-indigo-50 dark:ring-indigo-900/30" />
                <div className="flex flex-col">
                  <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider mb-1">
                    {step.month}
                  </span>
                  <p className="text-gray-700 dark:text-gray-300 font-medium bg-gray-50 dark:bg-slate-700/50 p-3 rounded-lg border border-gray-100 dark:border-slate-700">
                    {step.action}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      </div>
      
      <div className="flex justify-center pt-8">
        <button 
          onClick={() => navigate('/check')}
          className="flex items-center space-x-2 text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 font-medium transition-colors"
        >
          <RefreshCw className="w-4 h-4" />
          <span>Start New Analysis</span>
        </button>
      </div>

      <AIChatBox financialData={data} financialResult={result} />
    </div>
  );
};
